### ISSUE TITLE
is this repo up to date ?

### ISSUE THREAD

**Issue by tofke** [cubex-network/cubex#7]
Hi guys. I just compiled this source tree from scratch on an ARM (aarch64) VPS as i did previously with v1 (from previous github at https://github.com/cubexteam/cub), and i end up with binaries in version 1.0 !?

141 tof@mn2:~/github/cub⟫ git show HEAD|head
commit 141b35a6f63d7b09c8de31b6b918202f94373361
Author: Mona Lisa <dev@home33.io>
Date:   Thu Apr 26 13:34:30 2018 +0200

    release v1.0

diff --git a/.gitattributes b/.gitattributes
new file mode 100755
index 0000000..dfe0770
--- /dev/null
tof@mn2:~/github/cub⟫ cd ../cubex/
tof@mn2:~/github/cubex⟫ git show HEAD|head
commit c37c88bb76bad00be63e1c985111e1fcc259bcbd
Author: dr4ge <dr4ge@mail.com>
Date:   Thu Jun 28 21:02:07 2018 +0200

    release v2.0.0.0. repo upload

diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
new file mode 100755
index 0000000..92266eb
--- /dev/null
tof@mn2:~/github/cubex⟫ ./src/cub-cli -version
Cub RPC client version v1.0.0.0-c37c88b-dr4ge

**Comment by cubex-network** [comment]
open  <repo>/src/config/cub-config.h 
#define CLIENT_VERSION_MAJOR 1
change to 
#define CLIENT_VERSION_MAJOR 2
